[token]
symbol = "BTC"
name = "Bitcoin"
precision = 4

faucet = "CEbVVUzzmJKUEhiAoAiCbRvXEmMw92ZhzUv1yiMd2Ybn"
faucet_limit = 1_000_000

[config]
mint = "3PjEttgLvBxa1pYZhUJbwXRdB7KkXJWKuPxj8Ly65tVj"
pyth_price = "GJp622VronyrMkbS423pVgdx19FwCEVzNfMvDbrRriV1"
pyth_product = "5MhM4ooa18waRNZhkg99YF5W5TuXRmTokkL9qtcztXUe"

token_kind = 'Collateral'
collateral_weight = 90
max_leverage = 15_00

[margin_pool]
flags = 0b0010 # ALLOW_LENDING
utilization_rate_1 = 85_00
utilization_rate_2 = 95_00
borrow_rate_0 = 50
borrow_rate_1 = 600
borrow_rate_2 = 4000
borrow_rate_3 = 16000
management_fee_rate = 20_00
management_fee_collect_threshold = 1_000