[package]
name = "jet-bonds-lib"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]

# Builder 
agnostic-orderbook = { git = "https://github.com/jet-lab/agnostic-orderbook.git", branch = "main", features = ["lib", "utils"] }
thiserror = { version = "1" }
rand = { version = "0.8.5" }
solana-sdk = { version = "1.9" }
spl-token = { version = "3.1.0" }
spl-associated-token-account = { version = "1.0" }

jet-bonds = { path = "../../../programs/bonds", features = ["no-entrypoint"] }
jet-metadata = { path = "../../../programs/metadata", features = ["no-entrypoint"] }

jet-simulation = { git = "https://github.com/jet-lab/jet-simulation", branch = "master" }
anchor-lang = { git = "https://github.com/jet-lab/anchor", branch = "master" }


