version: '3'

services:
  mongodb:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    restart: always
    ports:
      - 27017:27017
  postgres:
    image: gcr.io/kubernetes-608504/jet-data-postgres:development
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=flightlogs
    restart: always
    ports:
      - 5432:5432
  api:
    image: gcr.io/kubernetes-608504/jet-data-v2-black-box:development
    environment:
      - DATABASE_URL=postgres://postgres:password123@postgres:5432/flightlogs
      - MONGODB_CLIENT=mongodb://admin:password123@mongodb:27017
      - SOLANA_ENDPOINT=http://host.docker.internal:8899
      - RUST_LOG=sqlx::query=warn,sqlx=trace,hyper=warn,tokio=error,black_box=trace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3002:3002
    restart: always
  poller:
    image: gcr.io/kubernetes-608504/jet-data-v2-eventpoller:development
    environment:
      - POLLER_PROGRAMS=JPMRGNgRk3w2pzBM1RLNBnpGxQYsFQ3yXKpuk4tTXVZ,JPCtrLreUqsEbdhtxZ8zpd8wBydKz4nuEjX5u9Eg5H8,JPPooLEqRo3NCSx82EdE2VZY5vUaSsgskpZPBHNGVLZ,JPSmU9t1Hc6CqjPxqxUSAZLtAAdxxCSdH8Y1vo4xuWG,JPMAa5dnWLFRvUsumawFcGhnwikqZziLLfqn9SLNXPN,JPMetawzxw7WyH3qHUVScYHWFBGhjwqDnM2R9qVbRLp,JPASMkxARMmbeahk37H8PAAP1UzPNC4wGhvwLnBsfHi,JPTermEg2DwrV39xb1Fs7z1VUxcvdPT7mE7cyGsQ4xt
      - SOLANA_ENDPOINT=http://host.docker.internal:8899
      - MONGODB_CLIENT=mongodb://admin:password123@mongodb:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  parser:
    image: gcr.io/kubernetes-608504/jet-data-v2-eventparser:development
    environment:
      - SOLANA_ENDPOINT=http://host.docker.internal:8899
      - DATABASE_URL=postgres://postgres:password123@postgres:5432/flightlogs
      - MONGODB_CLIENT=mongodb://admin:password123@mongodb:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  pricefeeds:
    image: gcr.io/kubernetes-608504/jet-data-v2-pricefeeds:development
    environment:
      - SOLANA_ENDPOINT=http://host.docker.internal:8899
      - DATABASE_URL=postgres://postgres:password123@postgres:5432/flightlogs
      - MONGODB_CLIENT=mongodb://admin:password123@mongodb:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  swap:
    image: gcr.io/kubernetes-608504/jet-swap-api:latest
    environment:
      - DGRAPH_ENDPOINT=http://dgraphswap:9080
      - SOLANA_ENDPOINT=http://host.docker.internal:8899
      - SERVER_PORT=3005
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3005:3005
    restart: always
  dgraphswap:
    image: dgraph/standalone:v21.12.0
    restart: always
