anchor_version = "0.24.2"
solana_version = "1.10.29"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[features]
skip-lint = true

[programs.devnet]
jet_test_service = "JPTSApMSqCHBww7vDhpaSmzipTV3qPg6vxub4qneKoy"
jet_fixed_term = "JBond79m9K6HqYwngCjiJHb311GTXggo46kGcT2GijUc"
jet_control = "JPCtrLreUqsEbdhtxZ8zpd8wBydKz4nuEjX5u9Eg5H8"
jet_airspace = "JPASMkxARMmbeahk37H8PAAP1UzPNC4wGhvwLnBsfHi"
jet_margin = "JPMRGNgRk3w2pzBM1RLNBnpGxQYsFQ3yXKpuk4tTXVZ"
jet_margin_pool = "JPPooLEqRo3NCSx82EdE2VZY5vUaSsgskpZPBHNGVLZ"
jet_margin_swap = "JPMAa5dnWLFRvUsumawFcGhnwikqZziLLfqn9SLNXPN"
jet_metadata = "JPMetawzxw7WyH3qHUVScYHWFBGhjwqDnM2R9qVbRLp"

[programs.localnet]
jet_test_service = "JPTSApMSqCHBww7vDhpaSmzipTV3qPg6vxub4qneKoy"
jet_fixed_term = "JBond79m9K6HqYwngCjiJHb311GTXggo46kGcT2GijUc"
jet_control = "JPCtrLreUqsEbdhtxZ8zpd8wBydKz4nuEjX5u9Eg5H8"
jet_airspace = "JPASMkxARMmbeahk37H8PAAP1UzPNC4wGhvwLnBsfHi"
jet_margin = "JPMRGNgRk3w2pzBM1RLNBnpGxQYsFQ3yXKpuk4tTXVZ"
jet_margin_pool = "JPPooLEqRo3NCSx82EdE2VZY5vUaSsgskpZPBHNGVLZ"
jet_margin_swap = "JPMAa5dnWLFRvUsumawFcGhnwikqZziLLfqn9SLNXPN"
jet_metadata = "JPMetawzxw7WyH3qHUVScYHWFBGhjwqDnM2R9qVbRLp"
pyth = "FT9EZnpdo3tPfUCGn8SBkvN9DMpSStAg3YvAqvYrtSvL"

[[test.genesis]]
address = "DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1"
program = "./deps/spl-token-swap/mainnet_DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1_2022-06-20.so"

[[test.genesis]]
address = "9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP"
program = "./deps/spl-token-swap/mainnet_9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP_2022-06-20.so"

[[test.genesis]]
address = "4bXpkKSV8swHSnwqtzuboGPaPDeEgAn4Vt8GfarV5rZt"
program = "./deps/spl_token_faucet.so"

[[test.genesis]]
address = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"
program = "./deps/saber_stable_swap.so"

[[test.genesis]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
program = "./deps/orca_whirlpool_swap.so"

[[test.genesis]]
address = "SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8"
program = "./deps/spl-token-swap/crates.io-spl_token_swap==2.0.0.so"

[test]
startup_wait = 10000

[scripts]
test = "tests/scripts/anchor.sh"
