[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
jet_control = "JPCtrLreUqsEbdhtxZ8zpd8wBydKz4nuEjX5u9Eg5H8"
jet_margin = "JPMRGNgRk3w2pzBM1RLNBnpGxQYsFQ3yXKpuk4tTXVZ"
jet_margin_pool = "JPPooLEqRo3NCSx82EdE2VZY5vUaSsgskpZPBHNGVLZ"
jet_margin_swap = "JPMAa5dnWLFRvUsumawFcGhnwikqZziLLfqn9SLNXPN"
jet_metadata = "JPMetawzxw7WyH3qHUVScYHWFBGhjwqDnM2R9qVbRLp"

[programs.localnet]
jet_control = "JPCtrLreUqsEbdhtxZ8zpd8wBydKz4nuEjX5u9Eg5H8"
jet_margin = "JPMRGNgRk3w2pzBM1RLNBnpGxQYsFQ3yXKpuk4tTXVZ"
jet_margin_pool = "JPPooLEqRo3NCSx82EdE2VZY5vUaSsgskpZPBHNGVLZ"
jet_margin_swap = "JPMAa5dnWLFRvUsumawFcGhnwikqZziLLfqn9SLNXPN"
jet_metadata = "JPMetawzxw7WyH3qHUVScYHWFBGhjwqDnM2R9qVbRLp"
pyth = "FT9EZnpdo3tPfUCGn8SBkvN9DMpSStAg3YvAqvYrtSvL"

[[test.genesis]]
address = "9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP"
program = "./deps/orca_token_swap_v2.so"

[[test.genesis]]
address = "4bXpkKSV8swHSnwqtzuboGPaPDeEgAn4Vt8GfarV5rZt"
program = "./deps/spl_token_faucet.so"

[[test.genesis]]
address = "SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8"
program = "./deps/spl_token_swap.so"

[[test.genesis]]
address = "DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1"
program = "./deps/orca_token_swap_v1.so"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"