[package]
name = "jet-simulation"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
bincode = "1.3"
bytemuck = "1"
futures = "0.3"
parking_lot = "0.12"
rand = "0.7"
lazy_static = "1"
base64 = "0.13"
log = "0.4"
tokio = { version = "1", features = ["rt"] }

solana-account-decoder = "1.14.1"
solana-client = "1.14.1"
solana-sdk = "1.14.1"
solana-transaction-status = "1.14.1"
solana-runtime = "1.14.1"
solana-program-runtime = "1.14.1"
solana-bpf-loader-program = "1.14.1"
solana-program-test = "1.14.1"
solana-address-lookup-table-program = "1.14.1"

solana_rbpf = "0.2.31"