[token]
name = "BTC"
symbol = "BTC"
decimals = 6
precision = 2

max_test_amount = 10

collateral_weight = 75
max_leverage = 20_00

[margin_pool]
flags = 0b0010 # ALLOW_LENDING
utilization_rate_1 = 85_00
utilization_rate_2 = 95_00
borrow_rate_0 = 50
borrow_rate_1 = 600
borrow_rate_2 = 4000
borrow_rate_3 = 16000
management_fee_rate = 20_00