[token]
name = "USDC"
symbol = "USDC"
decimals = 6
precision = 2

max_test_amount = 1_000_000

collateral_weight = 1_00
max_leverage = 20_00

[margin_pool]
flags = 0b0010 # ALLOW_LENDING
utilization_rate_1 = 85_00
utilization_rate_2 = 95_00
borrow_rate_0 = 50
borrow_rate_1 = 600
borrow_rate_2 = 4000
borrow_rate_3 = 16000
management_fee_rate = 20_00

[[fixed_term_market]]
borrow_tenor = 86400
lend_tenor = 88000
min_order_size = 10
paused = false
ticket_price = 0.9
origination_fee = 10

[[fixed_term_market]]
borrow_tenor = 120
lend_tenor = 180
min_order_size = 10
paused = false
ticket_price = 0.9
origination_fee = 10

[[fixed_term_market]]
borrow_tenor = 604800
lend_tenor = 610000
min_order_size = 10
paused = false
ticket_price = 0.9
origination_fee = 10