[[dex]]
program = "spl-swap"
base = "BTC"
quote = "USDC"

[[dex]]
program = "spl-swap"
base = "BTC"
quote = "USDT"

[[dex]]
program = "saber-swap"
base = "USDT"
quote = "USDC"

[[dex]]
program = "openbook"
base = "BTC"
quote = "USDC"