name: Docker Builds

on:
  workflow_dispatch: {}
  push:
    branches: [master]
    paths:
      - 'lib/*'
      - 'public/*'
      - 'src/*'
      - 'package*'
      - 'craco.config.js'
      - 'tsconfig.json'
      - 'Dockerfile'

defaults:
  run:
    shell: bash

env:
  IMAGE_NAME: jet-v2-pools-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: sha
        run: echo "::set-output name=sha::$(echo '${{ github.event.after && github.event.after || github.sha }}' | cut -c 1-7)"

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          context: .
          tags: gcr.io/${{ secrets.GCP_PROJECT }}/${{ env.IMAGE_NAME }}:latest,gcr.io/${{ secrets.GCP_PROJECT }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.sha }}
