name: Lint

on:
  pull_request: {}
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  typescript:
    runs-on: ubuntu-latest
    env:
      REACT_APP_IP_REGISTRY: ${{ secrets.REACT_APP_IP_REGISTRY }}
      REACT_APP_RPC_DEV_TOKEN: ${{ secrets.REACT_APP_RPC_DEV_TOKEN }}
      REACT_APP_RPC_TOKEN: ${{ secrets.REACT_APP_RPC_TOKEN }}
      REACT_APP_LOGROCKET_PROJECT: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Install Testing tools
        run: npm install -g serve

      - name: Install Dependencies
        run: npm ci

      - name: Prettier Check
        run: npm run fmt

      - name: ESLint Check
        run: npm run lint

      - name: Jest Tests
        run: npm run test

      - name: clean up
        run: rm -rf ./build

      - name: Build
        run: npm run build:docker

      - name: E2E
        run: npm run e2e:ci
