[token]
symbol = "mSOL"
name = "Marinade Staked SOL"
precision = 2

[config]
mint = "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So"
pyth_price = "E4v1BBgoso9s64TQvmyownAVJbhbEPGyzA3qn4n46qj9"
pyth_product = "BS2iAqT67j8hA9Jji4B8UpL3Nfw9kwPfU5s4qeaf1e7r"

token_kind = 'Collateral'
collateral_weight = 80
max_leverage = 10_00

[margin_pool]
flags = 0b0010 # ALLOW_LENDING
utilization_rate_1 = 85_00
utilization_rate_2 = 95_00
borrow_rate_0 = 50
borrow_rate_1 = 600
borrow_rate_2 = 4000
borrow_rate_3 = 16000
management_fee_rate = 20_00