[package]
name = "jet-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = { version = "1", features = ["maths"] }
num-traits = "0.2"
thiserror = "1"
log = "0.4"
bytemuck = "1.7"
solana-sdk = "1.14"
solana-client = "1.14"

spl-associated-token-account = "1"

anchor-spl = { version = "0.27", features = ["dex"] }

jet-program-common = { path = "../program-common" }
jet-environment = { path = "../environment" }
jet-instructions = { path = "../instructions" }
jet-solana-client = { path = "../solana-client" }

spl-token = { version = "3", features = ["no-entrypoint"] }
mpl-token-metadata = { version = "1.7", features = ["no-entrypoint"] }

[dependencies.orca-whirlpool]
package = "whirlpool"
git = "https://github.com/jet-lab/whirlpools"
branch = "anchor-27"
features = ["no-entrypoint"]