[package]
name = "index"
version = "0.1.0"
edition = "2021"

# wasm-pack currently fails to install the correct binaryen version, so we disable wasm-opt for the time being
[package.metadata.wasm-pack.profile.release] 
wasm-opt = false

[lib]
path = "src/wasm-src/lib.rs"
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
testing = []

[dependencies]
anyhow = "1"
bytemuck = {version = "1.7.2", features = ["derive"] } 
serde = { version = "1.0", features = ["derive"] }
js-sys = "0.3.59"

wasm-bindgen = "0.2.83"
console_error_panic_hook = "0.1.7"

jet-program-common = { path = "../../libraries/rust/program-common" }
jet-fixed-term = { path = "../../programs/fixed-term" }

agnostic-orderbook = { git = "https://github.com/jet-lab/agnostic-orderbook.git", branch = "main", features = ["utils"]}

[dev-dependencies]
rand_chacha = "0.3.1"