[package]
name = "jet-solana-client"
version = "0.1.0"
edition = "2021"

[features]
client-native = ["solana-client"]
client-wasm = ["solana-client-wasm"]
default = ["client-native"]

[dependencies]
async-trait = "0.1"
thiserror = "1"
paste = "1.0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
bincode = "1.3"
base64 = "0.13"
log = "0.4"
tokio = { version = "1", features = ["time"] }

solana-sdk = "1.14"
solana-transaction-status = "1.14"
solana-account-decoder = "1.14"
solana-client = { version = "1.14", optional = true }
solana-client-wasm = { version = "1.14", optional = true }

spl-associated-token-account = { version = "1", features = ["no-entrypoint"] }
spl-token = { version = "3", features = ["no-entrypoint"] }

anchor-lang = "0.27"