[package]
name = "jet-solana-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
thiserror = "1"
paste = "1.0.11"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
base64 = "0.13"

solana-sdk = { workspace = true }

spl-associated-token-account = { workspace = true }
spl-token = { workspace = true }

anchor-lang = { workspace = true }

