[package]
name = "jet-solana-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
thiserror = "1"

serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
base64 = "0.13"

solana-sdk = "1.14"

spl-token = { version = "3", features = ["no-entrypoint"] }

anchor-lang = "0.27"