[package]
name = "wasm-utils"
version = "0.1.0"
edition = "2021"

# wasm-pack currently fails to install the correct binaryen version, so we disable wasm-opt for the time being
[package.metadata.wasm-pack.profile.release] 
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
testing = []

[dependencies]
anyhow = "1"
bytemuck = {version = "1.7.2", features = ["derive"] } 
serde = { version = "1.0", features = ["derive"] }
js-sys = "0.3.59"
wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }

jet-program-common = { path = "../../../rust/program-common" }

[dev-dependencies]
rand_chacha = "0.3.1"