[package]
name = "wasm-utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
testing = []

[dependencies]
anyhow = "1"
bytemuck = {version = "1.7.2", features = ["derive"] } 
serde = { version = "1.0", features = ["derive"] }
js-sys = "0.3.59"
wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }

jet-proto-math = { git = "https://github.com/jet-lab/program-libraries", branch = "fixed-point-math", features = ["fixed-point", "number"] }

[dev-dependencies]
rand = "0.8.5"