[package]
name = "jet-client-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4"
wasm-bindgen-derive = "0.1"
js-sys = "0.3"
web-sys = "0.3"
console_error_panic_hook = "0.1"
console_log = "0.2"
log = "0.4"

serde_json = "1"
bincode = "1"

gloo-net = "0.2.4"

solana-sdk = "1.10"
spl-token = "3"

jet-client = { path = "../client" }
#jet-margin-sdk = { path = "../margin" }