#!/bin/bash
set -xueo pipefail

# TODO Assert that script is being run from repo root

rm -rf ./test-ledger

rm -rf ./target
find . -name 'node_modules' -type d -prune -exec rm -rf {} \;

yarn --cwd apps/react-app clean
yarn --cwd packages/margin clean

rm -rf packages/wasm
git checkout -- packages/wasm
