[package]
name = "jet-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
log = "0.4"

solana-sdk = "1.14"
solana-address-lookup-table-program = "1.14"

lookup-table-registry-client = { git = "https://github.com/jet-lab/lookup-table-registry", branch = "main", default-features = false }
lookup-table-registry = { git = "https://github.com/jet-lab/lookup-table-registry", branch = "main", features = ["no-entrypoint"] }

jet-instructions = { path = "../instructions" }
jet-environment = { path = "../environment" }
jet-solana-client = { path = "../solana-client" }