[package]
name = "jet-client-native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
futures = "0.3"
anyhow = "1"

solana-client = { workspace = true }
solana-sdk = { workspace = true }

jet-client = { workspace = true }
jet-solana-client = { workspace = true }
jet-simulation = { workspace = true }
