[package]
name = "jet-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
wasm = ["jet-solana-client/client-wasm"]

[dependencies]
log = "0.4"
thiserror = "1"
async-trait = "0.1"
async-recursion = "1"
futures = "0.3"
bincode = "1.3"
base64 = "0.13"
cached = "0.40"
bytemuck = "1.7"
wasm-bindgen = "0.2.83"

chrono = "0.4"

serde_with = "1.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

solana-sdk = "1.14"

spl-token = "3"
spl-associated-token-account = "1"
spl-token-swap = { version = "3", features = ["no-entrypoint"] }
pyth-sdk-solana = "0.7.2"

anchor-lang = "0.27"
anchor-spl = { version = "0.27", features = ["dex"] }

agnostic-orderbook = { git = "https://github.com/jet-lab/agnostic-orderbook.git", branch = "fill-event", features = ["lib", "utils"] }

jet-solana-client = { path = "../solana-client" }
jet-program-common = { path = "../program-common" }
jet-instructions = { path = "../instructions" }
jet-environment = { path = "../environment" }
jet-test-service = { path = "../../../programs/test-service", features = ["no-entrypoint"] }
jet-fixed-term = { path = "../../../programs/fixed-term", features = ["no-entrypoint", "cli"] }
jet-airspace = { path = "../../../programs/airspace", features = ["no-entrypoint"] }
jet-control = { path = "../../../programs/control", features = ["no-entrypoint"] }
jet-margin = { path = "../../../programs/margin", features = ["no-entrypoint"] }
jet-metadata = { path = "../../../programs/metadata", features = ["no-entrypoint"] }
jet-margin-pool = { path = "../../../programs/margin-pool", features = ["no-entrypoint"] }
jet-margin-swap = { path = "../../../programs/margin-swap", features = ["no-entrypoint"] }

lookup-table-registry-client = { git = "https://github.com/jet-lab/lookup-table-registry", branch = "main", default-features = false }
lookup-table-registry = { git = "https://github.com/jet-lab/lookup-table-registry", branch = "main", default-features = false, features = ["no-entrypoint", "api"] }

[dependencies.solana-address-lookup-table-program]
package = "solana-address-lookup-table-program-gateway"
git = "https://github.com/jet-lab/lookup-table-registry"
branch = "main"
features = ["stub-all"]

[dependencies.orca-whirlpool]
package = "whirlpool"
git = "https://github.com/jet-lab/whirlpools"
branch = "anchor-27"
features = ["no-entrypoint"]

[dev-dependencies]
rand_chacha = "0.3.1"
tokio = { version = "1", features = ["rt-multi-thread"] }