[package]
name = "jet-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
thiserror = "1"
async-trait = "0.1"
async-recursion = "1"
futures = "0.3"
bincode = "1.3"
base64 = "0.13"
cached = "0.40"
bytemuck = "1.7"
wasm-bindgen = "0.2.83"

chrono = "0.4"

serde_with = "1.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

tokio = "1"

solana-sdk = { workspace = true }

spl-token = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token-swap = { workspace = true }
pyth-sdk-solana = { workspace = true }

anchor-lang = { workspace = true }

agnostic-orderbook = { workspace = true }

jet-solana-client = { workspace = true }
jet-program-common = { workspace = true }
jet-instructions = { workspace = true }
jet-environment = { workspace = true }
jet-test-service = { workspace = true }
jet-fixed-term = { workspace = true }
jet-airspace = { workspace = true }
jet-control = { workspace = true }
jet-margin = { workspace = true }
jet-metadata = { workspace = true }
jet-margin-pool = { workspace = true }
jet-margin-swap = { workspace = true }

[dev-dependencies]
rand_chacha = "0.3.1"
tokio = { workspace = true, features = ["rt-multi-thread"] }