[token]
symbol = "DAI"
name = "DAI (Wormhole)"
precision = 2

[config]
mint = "EjmyN6qEC1Tf1JxiG1ae7UTJhUxSwk1TCWNWqxWV4J6o"
pyth_price = "CtJ8EkqLmeYyGB8s4jevpeNsvmD4dxVR2krfsDLcvV8Y"
pyth_product = "8x8E2jtWjh7ux8pp971Ha3UNYJ8LPNrnPEfF7v5FGdA1"

token_kind = 'Collateral'

collateral_weight = 25
max_leverage = 7_00

# collateral_weight = 50 # 50% for now due to liquidity constraints
# max_leverage = 20_00


[margin_pool]
flags = 0b0010 # ALLOW_LENDING
utilization_rate_1 = 85_00
utilization_rate_2 = 95_00
borrow_rate_0 = 50
borrow_rate_1 = 600
borrow_rate_2 = 4000
borrow_rate_3 = 16000
management_fee_rate = 20_00