[token]
symbol = "ETH"
name = "Ether (Wormhole)"
precision = 2

[config]
mint = "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs"
pyth_price = "JBu1AL4obBcCMqKBBxhpWCNUt136ijcuMZLFvTP7iWdB"
pyth_product = "EMkxjGC1CQ7JLiutDbfYb7UKb3zm9SJcUmr1YicBsdpZ"

token_kind = 'Collateral'

collateral_weight = 45
max_leverage = 5_00

# collateral_weight = 90
# max_leverage = 15_00


[margin_pool]
flags = 0b0010 # ALLOW_LENDING
utilization_rate_1 = 85_00
utilization_rate_2 = 95_00
borrow_rate_0 = 50
borrow_rate_1 = 600
borrow_rate_2 = 4000
borrow_rate_3 = 16000
management_fee_rate = 20_00