[token]
symbol = "ORCA"
name = "Orca"
precision = 2

[config]
mint = "orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE"
pyth_price = "4ivThkX8uRxBpHsdWSqyXYihzKF3zpRGAUCqyuagnLoV"
pyth_product = "4jLix5Lb1iCcsyGTJZothqYCL4ndj62r9cVTpW9Mowsa"

token_kind = 'Collateral'

collateral_weight = 0
max_leverage = 1_00

# collateral_weight = 0
# max_leverage = 5_00

[margin_pool]
flags = 0b0000 # ALLOW_LENDING
utilization_rate_1 = 85_00
utilization_rate_2 = 95_00
borrow_rate_0 = 50
borrow_rate_1 = 600
borrow_rate_2 = 4000
borrow_rate_3 = 16000
management_fee_rate = 20_00
