[token]
symbol = "stSOL"
name = "Lido Staked SOL"
precision = 2

[config]
mint = "7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj"
pyth_price = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"
pyth_product = "ALP8SdU9oARYVLgLR7LrqMNCYBnhtnQz1cj6bwgwQmgj"

token_kind = 'Collateral'

collateral_weight = 20
# 0.85 - require excess collateral (accounting for debt) greater than value of debt itself!
max_leverage = 85 

# collateral_weight = 80
# max_leverage = 10_00

[margin_pool]
flags = 0b0010 # ALLOW_LENDING
utilization_rate_1 = 85_00
utilization_rate_2 = 95_00
borrow_rate_0 = 50
borrow_rate_1 = 600
borrow_rate_2 = 4000
borrow_rate_3 = 16000
management_fee_rate = 20_00