name: build

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  hosted-tests-localnet-batch1:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:rust-1.66.1-node-18.13.0-solana-1.13.7-anchor-0.26.0-1
    env:
      HOME: /home/tools
      BATCH: batch1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get hosted-tests-localnet cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-hosted-tests-localnet-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - run: ./check hosted-tests-localnet


  hosted-tests-localnet-batch2:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:rust-1.66.1-node-18.13.0-solana-1.13.7-anchor-0.26.0-1
    env:
      HOME: /home/tools
      BATCH: batch2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get hosted-tests-localnet cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-hosted-tests-localnet-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - run: ./check hosted-tests-localnet


  cargo-lint:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:rust-1.66.1-node-18.13.0-solana-1.13.7-anchor-0.26.0-1
    env:
      HOME: /home/tools
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get cargo-lint cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - run: ./check cargo-lint


  cargo-test:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:rust-1.66.1-node-18.13.0-solana-1.13.7-anchor-0.26.0-1
    env:
      HOME: /home/tools
      CODECOV: true
    steps:
      - uses: actions/checkout@v3

      - name: Get cargo-test cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - run: ./check cargo-test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true

  e2e:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:rust-1.66.1-node-18.13.0-solana-1.13.7-anchor-0.26.0-1
    env:
      HOME: /home/tools
      SOLANA_MAINNET_RPC: ${{ secrets.SOLANA_MAINNET_RPC }}
      REACT_APP_IP_REGISTRY: ${{ secrets.REACT_APP_IP_REGISTRY }}
      REACT_APP_RPC_DEV_TOKEN: ${{ secrets.REACT_APP_RPC_DEV_TOKEN }}
      REACT_APP_RPC_TOKEN: ${{ secrets.REACT_APP_RPC_TOKEN }}
      REACT_APP_LOGROCKET_PROJECT: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get anchor cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-e2e-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - name: E2E
        run: |
          chmod -R 777 /root
          SOLANA_LOGS=false ./check e2e
