name: build

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build_aarch64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-darwin
          toolchain: stable

      - name: Get cargo-macos cache
        uses: actions/cache@v3
        with:
          key: cargo-macos
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - name: Check Build Errors
        run: cargo check --target aarch64-apple-darwin


  anchor-test:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:solana-1.10.35-anchor-0.25.0-3
    env:
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get anchor-test cache
        uses: actions/cache@v3
        with:
          key: anchor-test
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - name: ./check anchor-test
        run: |
          chmod -R 777 /root
          ./check anchor-test


  hosted-tests-localnet-batch1:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-2
    env:
      HOME: /root
      BATCH: batch1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get hosted-tests-localnet cache
        uses: actions/cache@v3
        with:
          key: hosted-tests-localnet
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - run: ./check hosted-tests-localnet


  hosted-tests-localnet-batch2:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-2
    env:
      HOME: /root
      BATCH: batch2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get hosted-tests-localnet cache
        uses: actions/cache@v3
        with:
          key: hosted-tests-localnet
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - run: ./check hosted-tests-localnet


  cargo-lint:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-2
    env:
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get cargo-lint cache
        uses: actions/cache@v3
        with:
          key: cargo-lint
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/debug

      - run: ./check cargo-lint


  cargo-test:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-2
    env:
      HOME: /root
      CODECOV: true
    steps:
      - uses: actions/checkout@v3

      - name: Get cargo-test cache
        uses: actions/cache@v3
        with:
          key: cargo-test
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - run: ./check cargo-test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true
