name: build

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  anchor-test:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:e2e
    env:
      HOME: /root
      SOLANA_MAINNET_RPC: ${{ secrets.SOLANA_MAINNET_RPC }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get anchor-test cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-anchor-test-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - name: ./check anchor-test
        run: |
          chmod -R 777 /root
          ./check anchor-test


  hosted-tests-localnet-batch1:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:e2e
    env:
      HOME: /root
      BATCH: batch1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get hosted-tests-localnet cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-hosted-tests-localnet-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - run: ./check hosted-tests-localnet


  hosted-tests-localnet-batch2:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:e2e
    env:
      HOME: /root
      BATCH: batch2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get hosted-tests-localnet cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-hosted-tests-localnet-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - run: ./check hosted-tests-localnet


  cargo-lint:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:e2e
    env:
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get cargo-lint cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - run: ./check cargo-lint


  cargo-test:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:e2e
    env:
      HOME: /root
      CODECOV: true
    steps:
      - uses: actions/checkout@v3

      - name: Get cargo-test cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - run: ./check cargo-test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true

  e2e:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:e2e
    env:
      HOME: /root
      SOLANA_MAINNET_RPC: ${{ secrets.SOLANA_MAINNET_RPC }}
      REACT_APP_IP_REGISTRY: ${{ secrets.REACT_APP_IP_REGISTRY }}
      REACT_APP_RPC_DEV_TOKEN: ${{ secrets.REACT_APP_RPC_DEV_TOKEN }}
      REACT_APP_RPC_TOKEN: ${{ secrets.REACT_APP_RPC_TOKEN }}
      REACT_APP_LOGROCKET_PROJECT: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get anchor-test cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-e2e-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - name: E2E
        run: |
          chmod -R 777 /root
          ./check e2e-tests
