name: build

# env:
#   HOME: /root
  # cli-id: anchor-v0.25.dev-solana-1.10.24
  # rust-version: stable
  # docker-image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  # anchor_build:
  #   name: Anchor Build
  #   runs-on: ubuntu-latest
  #   container:
  #     image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
  #   env:
  #     HOME: /root
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: anchor build cache
  #       uses: actions/cache@v3
  #       with:
  #         key: cargo-bpf
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #           target/
  #           !target/idl
  #           !target/deploy
  #     - name: Build
  #       run: anchor build -- --features testing
  #     - name: Archive build artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: anchor-build
  #         path: |
  #           target/idl
  #           target/deploy

  # cargo_build:
  #   name: Cargo Build
  #   # runs-on: ubuntu-latest
  #   container:
  #     image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
  #   env:
  #     HOME: /root
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: cargo cache
  #       uses: actions/cache@v3
  #       with:
  #         key: cargo-x86
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #           target/debug
  #     - name: Build
  #       run: cargo build --tests --features testing
  #     # - name: Archive build artifacts
  #     #   uses: actions/upload-artifact@v3
  #     #   with:
  #     #     name: anchor-build
  #     #     path: target/debug

  build_aarch64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-darwin
          toolchain: stable

      - name: Get cargo-macos cache
        uses: actions/cache@v3
        with:
          key: cargo-macos
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - name: Check Build Errors
        run: cargo check --target aarch64-apple-darwin


  anchor-test:
    name: Typescript Integration Tests
    # needs: anchor_build
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
    env:
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Download anchor build artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: anchor-build
      #     path: target
      - name: Get anchor-test cache
        uses: actions/cache@v3
        with:
          key: anchor-test
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - name: TS Test
        run: |
          chmod -R 777 /root
          ./check anchor-test


  localnet-tests:
    runs-on: ubuntu-latest
    # needs: anchor_build
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v3
      # - name: Download anchor build artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: anchor-build
      #     path: target
      - name: Get cargo-test-localnet cache
        uses: actions/cache@v3
        with:
          key: cargo-test-localnet
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy

      - run: ls -R
      - run: ./check cargo-test-localnet


  cargo-check:
    runs-on: ubuntu-latest
    # needs: cargo_build 
    container:
      image: jetprotocol/builder:test
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v3

      - name: Get cargo-check cache
        uses: actions/cache@v3
        with:
          key: cargo-check
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/debug

      - name: Cargo check
        run: ./check cargo-check


  coverage:
    runs-on: ubuntu-latest
    # needs: cargo_build 
    container:
      image: jetprotocol/builder:test
    env:
      HOME: /root
      CODECOV: true
    steps:
      - uses: actions/checkout@v3

      - name: Get cargo-test cache
        uses: actions/cache@v3
        with:
          key: cargo-test
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/debug

      - name: Cargo test with coverage
        run: ./check cargo-test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true
