name: build

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  anchor-test:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:test
    env:
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get anchor-test cache
        run: |
          echo ls /root && ls /root
          echo pwd && pwd
          echo ls && ls
          mv $(pwd) /root/jet-v2
          mv /root/target-cache /root/jet-v2/target
        # uses: actions/cache@v3
        # with:
        #   key: anchor-test
        #   path: |
        #     ~/.cargo/registry/index/
        #     ~/.cargo/registry/cache/
        #     ~/.cargo/git/db/
        #     target/
        #     !target/idl
        #     !target/deploy

      - name: ./check anchor-test
        run: |
          chmod -R 777 /root
          cd /root/jet-v2
          ./check anchor-test


  hosted-tests-localnet-batch1:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:test
    env:
      HOME: /root
      BATCH: batch1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get hosted-tests-localnet cache
        run: |
          mv $(pwd) /root/jet-v2
          mv /root/target-cache /root/jet-v2/target
        # uses: actions/cache@v3
        # with:
        #   key: hosted-tests-localnet
        #   path: |
        #     ~/.cargo/registry/index/
        #     ~/.cargo/registry/cache/
        #     ~/.cargo/git/db/
        #     target/
        #     !target/idl
        #     !target/deploy

      - run: cd /root/jet-v2 && ./check hosted-tests-localnet


  hosted-tests-localnet-batch2:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:test
    env:
      HOME: /root
      BATCH: batch2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get hosted-tests-localnet cache
        run: |
          mv $(pwd) /root/jet-v2
          mv /root/target-cache /root/jet-v2/target
        # uses: actions/cache@v3
        # with:
        #   key: hosted-tests-localnet
        #   path: |
        #     ~/.cargo/registry/index/
        #     ~/.cargo/registry/cache/
        #     ~/.cargo/git/db/
        #     target/
        #     !target/idl
        #     !target/deploy

      - run: cd /root/jet-v2 && ./check hosted-tests-localnet


  cargo-lint:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:test
    env:
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get cargo-lint cache
        run: |
          mv $(pwd) /root/jet-v2
          mv /root/target-cache /root/jet-v2/target
        # uses: actions/cache@v3
        # with:
        #   key: cargo-lint
        #   path: |
        #     ~/.cargo/registry/index/
        #     ~/.cargo/registry/cache/
        #     ~/.cargo/git/db/
        #     target/debug

      - run: cd /root/jet-v2 && ./check cargo-lint


  cargo-test:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:test
    env:
      HOME: /root
      CODECOV: true
    steps:
      - uses: actions/checkout@v3

      - name: Get cargo-test cache
        run: |
          mv $(pwd) /root/jet-v2
          mv /root/target-cache /root/jet-v2/target
        # uses: actions/cache@v3
        # with:
        #   key: cargo-test
        #   path: |
        #     ~/.cargo/registry/index/
        #     ~/.cargo/registry/cache/
        #     ~/.cargo/git/db/
        #     target/

      - run: cd /root/jet-v2 && ./check cargo-test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true
