name: Devnet Deployment

on:
  push:
    branches: [master]
    paths:
      - "programs/**/*.rs"
      - "programs/**/*.toml"
      - "tests/**/*.ts"
  workflow_dispatch: {}

env:
  ANCHOR_CLI_VERSION: 0.23.0
  SOLANA_CLI_VERSION: 1.10.8
  VALIDATOR_IMG: jet-v2-test-validator

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          key: cache-${{ runner.os }}-a${{ env.ANCHOR_CLI_VERSION }}-s${{ env.SOLANA_CLI_VERSION }}
          path: |
            ~/.cache/solana
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.local/share/solana/

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Solana
        run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Recover Cache
        uses: actions/cache@v3
        with:
          key: cache-${{ runner.os }}-a${{ env.ANCHOR_CLI_VERSION }}-s${{ env.SOLANA_CLI_VERSION }}
          path: |
            ~/.cache/solana
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.local/share/solana/

      - id: sha
        run: echo "::set-output name=sha::$(echo '${{ github.event.after && github.event.after || github.sha }}' | cut -c 1-7)"

      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get -y install pkg-config build-essential libudev-dev

      - name: Setup NPM
        uses: actions/setup-node@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install Anchor CLI
        run: npm i -g yarn @project-serum/anchor-cli@${{ env.ANCHOR_CLI_VERSION }}

      - name: Setup Environment
        run: |
          echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV \
          && mkdir -p ~/.config/solana \
          && mkdir -p ./target/deploy \
          && echo ${{ secrets.SOLANA_DEVNET_DEPLOYER_KEYPAIR }} > ~/.config/solana/id.json

      - name: Build Programs with Devnet
        run: |
          yarn install
          cargo fmt -- --check
          cargo clippy -- -D warnings
          anchor build --skip-lint -- --features testing devnet

      - name: Deploy Metadata
        run: |
          solana program deploy -u d --program-id JPMetawzxw7WyH3qHUVScYHWFBGhjwqDnM2R9qVbRLp target/deploy/jet_metadata.so
          anchor idl upgrade -f ./target/idl/jet_metadata.json JPMetawzxw7WyH3qHUVScYHWFBGhjwqDnM2R9qVbRLp --provider.cluster devnet

      - name: Deploy Control
        run: |
          solana program deploy -u d --program-id JPCtrLreUqsEbdhtxZ8zpd8wBydKz4nuEjX5u9Eg5H8 target/deploy/jet_control.so
          anchor idl upgrade -f ./target/idl/jet_control.json JPCtrLreUqsEbdhtxZ8zpd8wBydKz4nuEjX5u9Eg5H8 --provider.cluster devnet

      - name: Deploy Margin
        run: |
          solana program deploy -u d --program-id JPMRGNgRk3w2pzBM1RLNBnpGxQYsFQ3yXKpuk4tTXVZ target/deploy/jet_margin.so
          anchor idl upgrade -f ./target/idl/jet_margin.json JPMRGNgRk3w2pzBM1RLNBnpGxQYsFQ3yXKpuk4tTXVZ --provider.cluster devnet

      - name: Deploy Margin Pool
        run: |
          solana program deploy -u d --program-id JPPooLEqRo3NCSx82EdE2VZY5vUaSsgskpZPBHNGVLZ target/deploy/jet_margin_pool.so
          anchor idl upgrade -f ./target/idl/jet_margin_pool.json JPPooLEqRo3NCSx82EdE2VZY5vUaSsgskpZPBHNGVLZ --provider.cluster devnet

      - name: Deploy Margin Swap
        run: |
          solana program deploy -u d --program-id JPMAa5dnWLFRvUsumawFcGhnwikqZziLLfqn9SLNXPN target/deploy/jet_margin_swap.so
          anchor idl upgrade -f ./target/idl/jet_margin_swap.json JPMAa5dnWLFRvUsumawFcGhnwikqZziLLfqn9SLNXPN --provider.cluster devnet

      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          context: .
          tags: gcr.io/${{ secrets.GCP_PROJECT }}/${{ env.VALIDATOR_IMG }}:latest,gcr.io/${{ secrets.GCP_PROJECT }}/${{ env.VALIDATOR_IMG }}:${{ steps.sha.outputs.sha }}
          build-args: |
            SOLANA_VERSION=${{ env.SOLANA_CLI_VERSION }}
