name: Publish Docs

on:
  push:
    branches: 
      - "master"
    paths:
      - "programs"
      - "libraries/ts/src/**"
  workflow_dispatch: {}

jobs:
  changed_files_ts:
    runs-on: ubuntu-latest
    outputs:
      ts-docs: ${{steps.check-if-files-changed.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Check if any file in ts library has changed
        id: check-if-files-changed
        uses: tj-actions/changed-files@v29.0.3
        with:
          files: |
            libraries/ts

  changed_files_rust:
    runs-on: ubuntu-latest
    outputs:
      rust-docs: ${{steps.check-if-files-changed.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Check if any file in margin programs has changed
        id: check-if-files-changed
        uses: tj-actions/changed-files@v29.0.3
        with:
          files: |
            programs

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: [changed_files_ts, changed_files_rust] 
    if: needs.changed_files_ts.outputs.ts-docs == 'true' || needs.changed_files_rust.outputs.rust-docs == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build TS Documentation
        working-directory: ./libraries/ts
        run: yarn docs 

      - name: Build Rust Documentation
        run: yarn docs:rust

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: docs
