name: e2e

on:
  push:
    branches:
      - "master"
  pull_request: {}
  workflow_dispatch: {}

jobs:
  typescript:
    runs-on: ubuntu-latest
      env:
      REACT_APP_IP_REGISTRY: ${{ secrets.REACT_APP_IP_REGISTRY }}
      REACT_APP_RPC_DEV_TOKEN: ${{ secrets.REACT_APP_RPC_DEV_TOKEN }}
      REACT_APP_RPC_TOKEN: ${{ secrets.REACT_APP_RPC_TOKEN }}
      REACT_APP_LOGROCKET_PROJECT: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Clean Up Previous Build
        run: rm -rf ./app/build

      - name: Build All
        run: yarn build:all

      - name: E2E
        run: yarn test:ci
