name: Publish TS Doc

on:
  push:
    branches: 
      - "master"
    paths:
      - "libraries/ts"
  workflow_dispatch: {}

jobs:
  changed_files:
    runs-on: ubuntu-latest
    outputs:
      ts-docs: ${{steps.check-if-files-changed.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Check if any file in ts library has changed
        id: check-if-files-changed
        uses: tj-actions/changed-files@v29.0.3
        with:
          files: |
            libraries/ts

  build:
    runs-on: ubuntu-latest
    # needs: changed_files
    # if: needs.changed_files.outputs.ts-docs == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Documentation
        working-directory: ./libraries/ts
        run: yarn docs 
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: ts-client
          target-folder: ts-client
