name: build

# env:
#   HOME: /root
  # cli-id: anchor-v0.25.dev-solana-1.10.24
  # rust-version: stable
  # docker-image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  # anchor_build:
  #   name: Anchor Build
  #   runs-on: ubuntu-latest
  #   container:
  #     image: jetprotocol/builder:test
  #   # env:
  #   #   HOME: /root
  #   steps:
  #     # - id: cache-anchor-build
  #     #   uses: actions/cache@v3
  #     #   with:
  #     #     key: cache-anchor-build
  #     #     path: |
  #     #       ~/.cache/act
  #     #       ~/.cache/solana
  #     #       ~/.cargo/bin/
  #     #       ~/.cargo/registry/index/
  #     #       ~/.cargo/registry/cache/
  #     #       ~/.cargo/git/db/
  #     #       ~/.local/share/solana/
  #     #       ~/.npm

  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: TS Test
  #       run: anchor build -- --features testing

  # cargo_build:
  #   name: Cargo Build
  #   runs-on: ubuntu-latest
  #   container:
  #     image: jetprotocol/builder:test
  #   # env:
  #   #   HOME: /root
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: TS Test
  #       run: cargo build -- --features testing

  build_aarch64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-darwin
          toolchain: stable

      - name: Check Build Errors
        run: cargo check --target aarch64-apple-darwin

  ts_test:
    name: Typescript Integration Tests
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
    env:
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: TS Test
        run: |
          chmod -R +r /root
          npm ci
          whoami
          pwd
          ls -la /root/
          ls -la /root/.config/solana
          ls -la /github
          ls -la /github/home
          ls -la /github/home/workflow || echo no workflow
          echo "starting tests soon"
          whoami && cat /root/.config/solana/id.json || echo hmm
          whoami && anchor test -- --features testing || ec=$?
          echo "test exit code $ec"
          exit $ec

  localnet-tests:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v3
      - run: rustc --print target-list
      - run: tests/hosted/test_on_localnet.sh

  coverage:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v3

      - name: Clippy Check
        run: cargo clippy --all-targets -- -Dwarnings

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check docs
        run: cargo test --doc

      - name: Generate code coverage
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info --ignore-filename-regex programs/mock-pyth/src/lib.rs

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true
