name: build

# env:
#   HOME: /root
  # cli-id: anchor-v0.25.dev-solana-1.10.24
  # rust-version: stable
  # docker-image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  ts_test:
    name: Typescript Integration Tests
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
    env:
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: TS Test
        run: |
          npm ci
          whoami
          pwd
          ls -l /root/
          ls -l /root/.config/solana
          anchor test -- --features testing

  build_aarch64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-darwin
          toolchain: stable

      - name: Check Build Errors
        run: cargo check --target aarch64-apple-darwin

  localnet-tests:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v3
      - run: rustc --print target-list
      - run: tests/hosted/test_on_localnet.sh

  coverage:
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v3

      - name: Clippy Check
        run: cargo clippy --all-targets -- -Dwarnings

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check docs
        run: cargo test --doc

      - name: Generate code coverage
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info --ignore-filename-regex programs/mock-pyth/src/lib.rs

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true
