name: build

# env:
#   HOME: /root
  # cli-id: anchor-v0.25.dev-solana-1.10.24
  # rust-version: stable
  # docker-image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  # anchor_build:
  #   name: Anchor Build
  #   runs-on: ubuntu-latest
  #   container:
  #     image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
  #   env:
  #     HOME: /root
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: anchor build cache
  #       uses: actions/cache@v3
  #       with:
  #         key: cargo-bpf
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #           target/
  #           !target/idl
  #           !target/deploy
  #     - name: Build
  #       run: anchor build -- --features testing
  #     - name: Archive build artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: anchor-build
  #         path: |
  #           target/idl
  #           target/deploy

  # cargo_build:
  #   name: Cargo Build
  #   # runs-on: ubuntu-latest
  #   container:
  #     image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
  #   env:
  #     HOME: /root
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: cargo cache
  #       uses: actions/cache@v3
  #       with:
  #         key: cargo-x86
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #           target/debug
  #     - name: Build
  #       run: cargo build --tests --features testing
  #     # - name: Archive build artifacts
  #     #   uses: actions/upload-artifact@v3
  #     #   with:
  #     #     name: anchor-build
  #     #     path: target/debug

  build_aarch64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-darwin
          toolchain: stable
      - name: macos cargo cache
        uses: actions/cache@v3
        with:
          key: cargo-macos
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - name: Check Build Errors
        run: cargo check --target aarch64-apple-darwin

  ts_test:
    name: Typescript Integration Tests
    # needs: anchor_build
    runs-on: ubuntu-latest
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
    env:
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Download anchor build artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: anchor-build
      #     path: target
      - name: anchor build cache
        uses: actions/cache@v3
        with:
          key: cargo-bpf
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy
      - name: TS Test
        run: |
          set -x
          chmod -R 777 /root
          npm ci
          anchor test -- --features testing

  localnet-tests:
    runs-on: ubuntu-latest
    # needs: anchor_build
    container:
      image: jetprotocol/builder:root-solana1.10.35-anchor0.25.0-1
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v3
      # - name: Download anchor build artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: anchor-build
      #     path: target
      - name: anchor build cache
        uses: actions/cache@v3
        with:
          key: cargo-bpf
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !target/idl
            !target/deploy
            !target/debug
      - name: cargo test cache
        uses: actions/cache@v3
        with:
          key: cargo-x86
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/debug
      - run: rustc --print target-list
      - run: tests/hosted/test_on_localnet.sh

  coverage:
    runs-on: ubuntu-latest
    # needs: cargo_build 
    container:
      image: jetprotocol/builder:test
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v3
      - name: cargo test cache
        uses: actions/cache@v3
        with:
          key: cargo-x86
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/debug

      - name: Clippy Check
        run: cargo clippy --all-targets -- -Dwarnings

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check docs
        run: cargo test --doc

      - name: Generate code coverage
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info --ignore-filename-regex programs/mock-pyth/src/lib.rs

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true
