name: build

env:
  SOLANA_VERSION: 1.10.23
  ANCHOR_CLI_VERSION: 0.24.2

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  ts_test:
    name: Typescript Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: CacheTSDeps
        uses: actions/cache@v2
        with:
          key: cache-${{ runner.os }}-a${{ env.ANCHOR_CLI_VERSION }}-s${{ env.SOLANA_VERSION }}
          path: |
            ~/.cache/act
            ~/.cache/solana
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.local/share/solana/
            ~/.npm

      - name: Install Rust
        if: steps.CacheTSDeps.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - id: install-os-deps
        if: steps.CacheTSDeps.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: Install Solana
        if: steps.CacheTSDeps.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"

      - run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor CLI
        run: npm i -g @project-serum/anchor-cli@${{ env.ANCHOR_CLI_VERSION }}

      - run: npm ci

      - run: solana-keygen new --no-bip39-passphrase

      - name: TS Test
        run: npm run test
