[package]
name = "jet-fixed-terms-crank-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3.2", features = ["derive", "env"] }
tokio = { version = "1.0", features = ["time", "rt"] }
toml = "0.5"

anchor-lang = { git = "https://github.com/jet-lab/anchor", branch = "temp-version-bump-1-11" }

solana-client = "1.11"
solana-cli-config = "1.11"
solana-clap-utils = "1.11"
solana-sdk = "1.11"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

agnostic-orderbook = { git = "https://github.com/jet-lab/agnostic-orderbook.git", branch = "main", features = ["lib", "utils"] }

jet-ctl-cli = { path = "../ctl" }
jet-margin-sdk = { path = "../../libraries/rust/margin" }
