[package]
name = "jet-markets-crank-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3.2", features = ["derive", "env"] }
tokio = { version = "1.0", features = ["time", "rt"] }

serde = { version = "1.0", features = ["derive"] }
serde_with = "1.5"
serde_json = "1.0"

jet-ctl-cli = { path = "../ctl" }
jet-margin-sdk = { path = "../../libraries/rust/margin" }
